### ISSUE TITLE
Weird Server error being logged for image loading

### ISSUE THREAD

**Issue by samolds** [samolds/principia#208]
This doesn't affect what the user sees (as far as I know), but i've been seeing this message logged on the server:

```
ERROR    2016-04-18 14:44:43,176 api_server.py:272] Exception while handling service_name: "images"
method: "GetUrlBase"
request: "\n\000"
request_id: "yrNjGLCeQA"

Traceback (most recent call last):
  File "/usr/local/go_appengine/google/appengine/tools/devappserver2/api_server.py", line 247, in _handle_POST
    api_response = _execute_request(request).Encode()
  File "/usr/local/go_appengine/google/appengine/tools/devappserver2/api_server.py", line 189, in _execute_request
    make_request()
  File "/usr/local/go_appengine/google/appengine/tools/devappserver2/api_server.py", line 181, in make_request
    request_id)
  File "/usr/local/go_appengine/google/appengine/api/images/images_not_implemented_stub.py", line 49, in MakeSyncCall
    self._blob_stub.GetUrlBase(request, response)
  File "/usr/local/go_appengine/google/appengine/api/images/images_blob_stub.py", line 60, in GetUrlBase
    BLOB_SERVING_URL_KIND, name=request.blob_key(), namespace='')
  File "/usr/local/go_appengine/google/appengine/api/datastore.py", line 811, in __init__
    datastore_types.ValidateString(name, 'name')
  File "/usr/local/go_appengine/google/appengine/api/datastore_types.py", line 181, in ValidateString
    raise exception('%s must not be empty.' % name)
BadValueError: name must not be empty.
```

I think it has something to do with how I'm saving images to the blobstore?

**Comment by samolds** [comment]
I haven't seen this since commit 16fe79a6a27052184a86ae4decce7a41739cbdec
